### ISSUE TITLE
Compare Reports

### ISSUE THREAD

**Issue by dalderson07** [tabulartools/pbi-explorer#16] opened 2023-09-24 19:40 UTC
Looks to be same as:
https://github.com/tabulartools/pbi-explorer/issues/14#issue-1910318866

### Describe the problem

Trying to compare two reports (essentially report 2 is a copy of report 1, with a few minor edits on a couple of pages). The window and dialogs to select the two reports open fine, but I receive the error below when confirming the selection of the second report.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.CompareArrayProperty(ReportCompareObject rootNode, String path, Type leftPropertyType, Type rightPropertyType, Object leftObject, Object rightObject, String propertyName, ILogger logger)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.Compare(ReportCompareObject rootNode, String path, Type leftType, Type rightType, Object leftObject, Object rightObject, String propertyName, ILogger logger)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.<>c__DisplayClass14_0.<CompareComplexProperty>b__2(String prop)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.Compare(ReportCompareObject rootNode, String path, Type leftType, Type rightType, Object leftObject, Object rightObject, String propertyName, ILogger logger)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.CompareListProperty(ReportCompareObject rootNode, String path, Type leftPropertyType, Type rightPropertyType, Object leftObject, Object rightObject, String propertyName, ILogger logger)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.Compare(ReportCompareObject rootNode, String path, Type leftType, Type rightType, Object leftObject, Object rightObject, String propertyName, ILogger logger)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.<>c__DisplayClass14_0.<CompareComplexProperty>b__2(String prop)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.Compare(ReportCompareObject rootNode, String path, Type leftType, Type rightType, Object leftObject, Object rightObject, String propertyName, ILogger logger)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.CompareListProperty(ReportCompareObject rootNode, String path, Type leftPropertyType, Type rightPropertyType, Object leftObject, Object rightObject, String propertyName, ILogger logger)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.Compare(ReportCompareObject rootNode, String path, Type leftType, Type rightType, Object leftObject, Object rightObject, String propertyName, ILogger logger)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.<>c__DisplayClass14_0.<CompareComplexProperty>b__2(String prop)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.Compare(ReportCompareObject rootNode, String path, Type leftType, Type rightType, Object leftObject, Object rightObject, String propertyName, ILogger logger)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.CompareListProperty(ReportCompareObject rootNode, String path, Type leftPropertyType, Type rightPropertyType, Object leftObject, Object rightObject, String propertyName, ILogger logger)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.Compare(ReportCompareObject rootNode, String path, Type leftType, Type rightType, Object leftObject, Object rightObject, String propertyName, ILogger logger)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.<>c__DisplayClass14_0.<CompareComplexProperty>b__2(String prop)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.Compare(ReportCompareObject rootNode, String path, Type leftType, Type rightType, Object leftObject, Object rightObject, String propertyName, ILogger logger)
   at PbiExplorer.Shared.Comparers.Generic.GenericObjectComparer.CompareReports(Report leftReport, Report rightReport, ILogger logger)
   at PbiExplorer.Shared.ReportService.CompareReports(Report leftReport, Report rightReport)
   at PbiExplorer.UI.Controllers.ReportComparerController.PerformComparison()
   at PbiExplorer.UI.Controllers.ReportComparerController.OpenFileRight(String fileName)
   at PbiExplorer.UI.Views.ReportComparerView.lblRightFileName_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraControl.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.BaseWndProc(Message& m)
   at DevExpress.XtraEditors.BaseControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Private.CoreLib.dll
----------------------------------------
PbiExplorer
    Assembly Version: 0.2.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.dll
----------------------------------------
DevExpress.Utils.v23.1
    Assembly Version: 23.1.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Forms
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Drawing.Common.dll
----------------------------------------
DevExpress.Data.v23.1
    Assembly Version: 23.1.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/netstandard.dll
----------------------------------------
System.Threading
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.Thread
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.Thread.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ObjectModel.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Private.Uri.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.Process.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.NonGeneric.dll
----------------------------------------
System.Memory
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Memory.dll
----------------------------------------
System.Security.Cryptography
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Security.Cryptography.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.WebClient.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Text.Encoding.Extensions.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Xml.XmlSerializer.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.dll
----------------------------------------
DevExpress.Data.Desktop.v23.1
    Assembly Version: 23.1.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
DevExpress.Drawing.v23.1
    Assembly Version: 23.1.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Numerics.Vectors.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.IO.Compression.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Linq.Expressions.dll
----------------------------------------
System.Linq
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Linq.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/Microsoft.Win32.SystemEvents.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/Microsoft.Win32.Registry.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.1123.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/Accessibility.dll
----------------------------------------
DevExpress.XtraBars.v23.1
    Assembly Version: 23.1.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
DevExpress.XtraEditors.v23.1
    Assembly Version: 23.1.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Text.RegularExpressions.dll
----------------------------------------
System.ComponentModel.Annotations
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.Annotations.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.Loader.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Resources.Extensions.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/mscorlib.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
DevExpress.XtraLayout.v23.1
    Assembly Version: 23.1.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
DevExpress.Printing.v23.1.Core
    Assembly Version: 23.1.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Drawing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Drawing.dll
----------------------------------------
DevExpress.XtraTreeList.v23.1
    Assembly Version: 23.1.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
PbiExplorer.Shared
    Assembly Version: 0.2.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.1774.30
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.1774.30
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
DevExpress.XtraVerticalGrid.v23.1
    Assembly Version: 23.1.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.Http
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Security.dll
----------------------------------------
System.Net.Quic
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Quic.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.ThreadPool.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.NameResolution.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Security.Claims.dll
----------------------------------------
Newtonsoft.Json.Schema
    Assembly Version: 3.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.Numerics.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Data.Common.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Windows.Extensions.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.Tasks.dll
----------------------------------------
PbiTools.ReportModel
    Assembly Version: 0.2.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO.Packaging
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.IO.Packaging.dll
----------------------------------------
PbiExplorer.Entities
    Assembly Version: 0.2.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.Immutable.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Reflection.Metadata.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.FileVersionInfo.dll
----------------------------------------

************** JIT Debugging **************

### Power BI

2.121.782.0

### Steps to reproduce the behavior

1. Open PBI Explorer
2. select compare reports
3. select original report
4. select compare report

### Screenshots

<img width="1434" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/111552042/02358cc6-132c-4a0b-9534-5a774d9b2d12">
<img width="1434" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/111552042/9e17aa50-d1e2-4f4c-8773-bcff2f444b96">

**Comment by DBojsen** [comment] 2023-09-24 22:18
Hi @dalderson07 

It is indeed the same issue as #14.
I’ll close this one and only track on one issue. 

If you can share a pbit (without data), that would be great - you can do so on #14 .

BR David - Tabular Tools

**Comment by DBojsen** [comment] 2023-09-24 22:18
Duplicate of #14

**Closed by DBojsen** 2023-09-24 22:18 UTC
Labels: bug, untriaged
