### ISSUE TITLE
Other people pbi Inpect report not error

### ISSUE THREAD

**Issue by emirtut** [tabulartools/pbi-explorer#15] opened 2023-09-24 18:43 UTC
### Describe the problem

Hi,
Pbi file created by somebody else, on my machine using pbi explorer, part Inspect report I got error on picture below.
I tried pbi file, very simple which I created and I do not receive this error. 

![image](https://github.com/tabulartools/pbi-explorer/assets/69401624/1ed468b9-0a5f-4b07-becc-8910b5807681)

![image](https://github.com/tabulartools/pbi-explorer/assets/69401624/d55db0e6-7492-487f-8695-435c6715b564)

### Power BI

Pbi version september 2023

### Steps to reproduce the behavior

On choose pbi explorer "Inspect report", when I select report.

**Comment by DBojsen** [comment] 2023-09-24 22:15
Hi @emirtut 

This is the same issue as #3 - I will close this as a duplicate. 

But thanks for reporting. 

BR David - Tabular Tools

**Comment by DBojsen** [comment] 2023-09-24 22:15
Duplicate of #3

**Closed by DBojsen** 2023-09-24 22:15 UTC
Labels: bug, untriaged
