### ISSUE TITLE
Offer the ability to show a list of measures and columns not used anywhere in the loaded report

### ISSUE THREAD

**Issue by corycundy** [tabulartools/pbi-explorer#82] opened 2024-01-16 03:17 UTC
### The feature request

When developing a Tabular Model, there are times when you experiment with measures and unintentionally leave intermediate or testing measures in the model. It would be nice to know which measures are part of a model that are not used in a report. It would be nice to identify these measures.

### Proposed solution

I propose having a place within the UI that will show measures and columns that are not used within any report visual. This would be most helpful when the model and report are together within a Power BI file, but also when connecting to a separate Semantic Model or Analysis Services model.

Care would have to be taken from the user to understand that when connecting to a remote model, that other reports might reference a measure or column when the specific report loaded in PBI Explorer may not. Despite this scenario, this would still be a very valuable feature to help clean up models or understand what is and isn't being used.

**Comment by DBojsen** [comment] 2024-01-16 11:08
Hi @corycundy 

This is a duplicate of #47

**Closed as completed by DBojsen** 2024-01-16 11:08 UTC
Labels: enhancement, untriaged
