### ISSUE TITLE
Won't open report - Unsupported Features, but worked fine a a few weeks ago

### ISSUE THREAD

**Issue by edhans** [tabulartools/pbi-explorer#49] opened 2023-10-16 16:13 UTC
### Describe the problem

![image](https://github.com/tabulartools/pbi-explorer/assets/45298358/d8974ccb-78cc-4135-888e-0a61a979fc51)

This report opened fine with PBI Explorer 0.3x. It is a thin report connected to a dataset via Live connection.

The report has since been saved using the Oct 2023 desktop, so not sure if that caused an issue or if there is an issue with the current 0.41 build I am using.

### PBI Explorer

0.4.1

### Power BI

Desktop October 2023

### Windows

Windows 10

### Steps to reproduce the behavior

Just opened the PBIX.

**Comment by DBojsen** [comment] 2023-10-20 08:57
Thanks for reporting @edhans 

We'll have a look.  Is it possible to share a pbit (without data), then we would appreciate if you can send it to support@tabulartools.com.

**Comment by mthierba** [comment] 2023-10-29 11:45
Please note we have identified the root cause (many thanks for providing the report via our support email!), hence can implement a fix now.

**Comment by DBojsen** [comment] 2023-11-24 12:04
This should be fixed with BETA5 (0.6.1) which we released yesterday.
If you still have the issue, please reopen.

**Closed as completed by DBojsen** 2023-11-24 12:04 UTC
Labels: bug, backlog
