### ISSUE TITLE
Error opening PBI file

### ISSUE THREAD

**Issue by 100DGuillory** [tabulartools/pbi-explorer#11] opened 2023-09-22 21:05 UTC
### Describe the problem

Tried to open a pbix file and PBI Explorer displayed the error in the below image.

### Power BI

PBI Desktop Version: 2.121.644.0 64-bit (September 2023)

### Screenshots

![F6pPSY8boAAicUJ](https://github.com/tabulartools/dax-optimizer/assets/26236433/bac77397-3a26-4aa6-82db-6e00c938ccc5)

**Comment by gerhardvdw65** [comment] 2023-09-23 10:22
Tried to open 3 different models with PBI Explorer and got 3 different errors.  (All 3 models currently in Production Environment)
![Model Open bug 2](https://github.com/tabulartools/pbi-explorer/assets/15626119/63a545af-af30-4d85-a377-d3dacb0a7c3d)
![Model Open bug 3](https://github.com/tabulartools/pbi-explorer/assets/15626119/6f8e194b-5100-4b01-85f9-e2a79f53206f)
![Model Open bug 4](https://github.com/tabulartools/pbi-explorer/assets/15626119/4ef58efd-7700-46ad-abb3-6f5c61440e98)

**Comment by DBojsen** [comment] 2023-09-24 10:01
Hi all

The original issue by @100DGuillory and the 2. and 3. screenshot by @gerhardvdw65 are the same issue and it is a duplicate of #3. (I'll close this issue and we'll track it there)

The 1. screenshot by @gerhardvdw65 is a separate issue, thet we'll be able to work on based on the screenshot, but it would be nice if you could create a separate issue for it to track it independently.

BR David - Tabular Tools

**Closed by DBojsen** 2023-09-24 10:01 UTC
Labels: bug, untriaged

**Comment by DBojsen** [comment] 2023-09-24 10:07
Duplicate of #3
