### ISSUE TITLE
Cannot open certain PBIX files

### ISSUE THREAD

**Issue by lbendlin** [tabulartools/pbi-explorer#8] opened 2023-09-22 16:33 UTC
### Describe the problem

![image](https://github.com/tabulartools/pbi-explorer/assets/1059103/d5abbbf7-e83d-4cd3-b83a-68b97a3c23c7)

### Power BI

September 2023

### Additional context

Doesn't seem to be file size related.  seems to work with files that are a bit older.

### Screenshots

![image](https://github.com/tabulartools/pbi-explorer/assets/1059103/813d634f-6418-4892-8210-abea25a0154d)
![image](https://github.com/tabulartools/pbi-explorer/assets/1059103/e934ddd3-745f-4622-98fc-b7d1c08b0f04)

**Comment by MikeCarlo** [comment] 2023-09-22 21:12
I have the same issue, this appears to be occurring on Older files for me. 

using a file that has the following report settings fails:

![image](https://github.com/tabulartools/pbi-explorer/assets/25160592/d0f19d19-a011-4e22-aa0d-0e300379f70b)

**Comment by KaelDowdy** [comment] 2023-09-22 21:58
@MikeCarlo  - I wonder what'd happen if you open the .PBIX causing the error in the most recent version of PBI Desktop, make a minor report change, and then save it.  Could it be some meta-data structure issues?  

Perhaps a .PBIX file initially created a year or two ago causes problems.  Wonder if you create a brand new .PBIX, then copy/all Power Query & data model objects from the old file to the new one (yes -- I know that can be an EXTREMELY DAUNTING task!!!).  Would that work around the issue?

**Comment by lbendlin** [comment] 2023-09-22 22:26
Doesn't seem to make a difference for me. Failures happen for brand new files as well as for older files. Maybe the use of custom visuals?On Sep 22, 2023 5:58 PM, Kael Dowdy ***@***.***> wrote:
@MikeCarlo  - I wonder what'd happen if you open the .PBIX causing the error in the most recent version of PBI Desktop, make a minor report change, and then save it.  Could it be some meta-data structure issues?
Perhaps a .PBIX file initially created a year or two ago causes problems.  Wonder if you create a brand new .PBIX, then copy/all Power Query & data model objects from the old file to the new one (yes -- I know that can be an EXTREMELY DAUNTING task!!!).  Would that work around the issue?

**Comment by gtmoten** [comment] 2023-09-23 01:17
I have the same problem as above with existing models. I created a new model, loaded a single XL file and added a table visual - no problems. I added the Chiclet Slicer expecting a problem, but that worked also. 🤷‍♂️

I will try a new test later with different data sources....

**Comment by DBojsen** [comment] 2023-09-24 09:54
Hi all

The original issue reported by @lbendlin is a duplicate of #3 that has to do with deserialization of filters.
I'll merge this issue into that one. 

I cannot tell if the comments by @MikeCarlo & @gtmoten is the same as they do not include the error popup with the stack trace.  If it is unrelated then please create new issues with the relevant info. 

BR David - Tabular Tools

**Closed by DBojsen** 2023-09-24 09:54 UTC
Labels: bug, untriaged

**Comment by DBojsen** [comment] 2023-09-24 10:08
Duplicate of #3
