### ISSUE TITLE
Unsupported feature - DQ, new Card viz, or something in Sept desktop

### ISSUE THREAD

**Issue by edhans** [tabulartools/pbi-explorer#21] opened 2023-09-25 18:27 UTC
### Describe the problem

I tried to open a **thin** report this morning and got this error.
![image](https://github.com/tabulartools/pbi-explorer/assets/45298358/f52c6019-5375-492e-922c-1fc68f41b0bd)

I then tried to open an August 25 version of the report and it opened fine. Other than a TON of DAX changes, only three things are different between the reports from a report perspective:

1. The report has been opened and saved using the Sept 2023 desktop build
2. The New Card viz was added to the report.
3. The model was 100% import, but now has 1 DirectQuery table to a database (not AAS/PBI). That very small DQ table (< 10 records usually) is used to populate the new card viz in 2 above.

Wasn't sure which one (or combo) is causing this error. 

### Power BI

Power BI Desktop September 2023

**Comment by DBojsen** [comment] 2023-09-27 07:49
Hi @edhans 

This is a duplicate of https://github.com/tabulartools/pbi-explorer/issues/20#issuecomment-1733803053 and is already being tracked there.
It is not an issue that this is a thin report - it is just an unexpected value in an object (that according to documentation shouldn't be there.  I'll leave this issue open and track it here

**Closed** 2023-09-27 13:37 UTC
Labels: bug, backlog
