### ISSUE TITLE
Documenting reports

### ISSUE THREAD

**Issue by rakshanNagesh0526** [tabulartools/pbi-explorer#45] opened 2023-10-04 16:58 UTC
### The feature request

Is there a feature to document reports, does not have to be exquisite, but it should create a word doc, which developers can use to show everything about the report in one place

### Proposed solution

Exportable in word doc or excel, which can be used to help business users understand how to use it

**Comment by DBojsen** [comment] 2023-10-04 20:40
This has already been suggested and answered here #25

**Comment by DBojsen** [comment] 2023-10-04 20:41
Duplicate of #25

**Comment by DBojsen** [comment] 2023-10-04 20:41
Duplicate of #25

**Closed as completed by DBojsen** 2023-10-04 20:41 UTC
Labels: enhancement, untriaged
