### ISSUE TITLE
We couldn't open the specified file. Most likely the file contains a feature not yet supported.

### ISSUE THREAD

**Issue by kerski** [tabulartools/pbi-explorer#4] opened 2023-09-22 14:58 UTC
### Describe the problem

I tried to open a .pbit file and got the message below:

![Screenshot 2023-09-22 105507](https://github.com/tabulartools/pbi-explorer/assets/85596845/69634c14-c2c4-4c7c-8548-d2b6d139bbb1)

### Power BI

2.121.762.0 64-bit (September 2023)

### Steps to reproduce the behavior

1. Inspect
2. Open .pbit file (ex: https://github.com/kerski/pbi-dataops-monitoring/releases/download/v1.2.0-beta/Power.BI.Monitoring.Template.-.Commercial.pbit)
3. Got error.

**Comment by DBojsen** [comment] 2023-09-24 09:46
Hi @kerski 

This issue is the same as #3 - closing this one and tracking there instead.

BR David - Tabular Tools

**Closed by DBojsen** 2023-09-24 09:46 UTC
Labels: bug, untriaged

**Comment by DBojsen** [comment] 2023-09-24 10:07
Duplicate of #3
