### ISSUE TITLE
Doesn't show one of the fact tables

### ISSUE THREAD

**Issue by fernandocalero** [tabulartools/pbi-explorer#57] opened 2023-11-13 18:17 UTC
### Describe the problem

I have two fact tables and it's only showing one. 
![figure1](https://github.com/tabulartools/pbi-explorer/assets/3391678/07f96bb4-d211-415c-8695-b3d5f0198361)
![figure2](https://github.com/tabulartools/pbi-explorer/assets/3391678/670f27c4-f708-4903-be5b-87ad69ea2122)

### PBI Explorer

0.5.1

### Power BI

Power BI Desktop Version: 2.122.1066.0 64-bit (October 2023)

### Windows

Windows 11 Home v. 10.0.22621 Build 22621

### Steps to reproduce the behavior

1. Report inspector
2. Data model explorer

### Screenshots

![figure1](https://github.com/tabulartools/pbi-explorer/assets/3391678/8f8494a9-4d30-4608-a653-333877c5c8e9)
![figure2](https://github.com/tabulartools/pbi-explorer/assets/3391678/c2cf13b4-a49f-4d68-8c04-4f0db629e1e5)

**Comment by DBojsen** [comment] 2023-11-13 18:24
Hi @fernandocalero 

This is a duplicate of 
#51. 
Please see the answer there: https://github.com/tabulartools/pbi-explorer/issues/51#issuecomment-1776835437

BR David - Tabular Tools

**Comment by DBojsen** [comment] 2023-11-13 18:43
This comment https://github.com/tabulartools/pbi-explorer/issues/51#issuecomment-1808784160 was made on a different issue, but is related to this one.

**Comment by DBojsen** [comment] 2023-11-13 18:46
Hi @fernandocalero 

Could you clarify how the measures and/or columns are used by the visuals of the report?
We have a few gaps in detecting all fields that are only used in filters, which will be fixes in next release. 
Also, custom visuals are not being taken into consideration yet. 

If you have standard visuals utilizing elements from the missing fact table, we’d love to know more.

**Comment by fernandocalero** [comment] 2023-11-13 18:55
Yes, almost all the objects - all standard - in the first page Summary Online use the measure Sum of Online SalesAmount. This measure is located in the Measures table, identically than the corresponding measures in the Summary Channels page that point to the FactSales table, which does show up in the Data Model Explorer. If you need it I could send you the pbix file, it's based on Contoso DB.
Thanks,
F
![figure1](https://github.com/tabulartools/pbi-explorer/assets/3391678/3fa1f41b-2ff6-434a-adde-33b6d0041f7c)

**Comment by DBojsen** [comment] 2023-11-13 19:00
Hi again

Since the measure is placed in the Measures folder, I would expect it to also show up there in PBI Explorer.
We do not have access to the DAX formulas and/or lineage information, so we have no way of telling, that it is utilizing information from that fact table.
In other words, we only show objects (measures, columns, hierarchylevels) that are **directly** used by a visual.

You should still be able to see where that measure is used, but not indirect usage through the measure.

Makes sense?

**Comment by fernandocalero** [comment] 2023-11-13 19:02
It does only if the FactSales table were hidden also, because has the same logic and it does show up in PBI Explorer.

**Comment by DBojsen** [comment] 2023-11-13 19:03
Could you please send the pbix to support@tabulartools.com, then I'll have a look ;-)

**Comment by fernandocalero** [comment] 2023-11-13 19:06
Yes, I'll send it right away. I just added a card visual with an implicit measure directly from the FactOnlineSales table and still doesn't show up in the Data Model Explorer.
![figure1](https://github.com/tabulartools/pbi-explorer/assets/3391678/3f699eea-6558-4126-bcb3-4aab814ff4ea)

**Comment by DBojsen** [comment] 2023-11-13 19:54
Hi again

I forgot to mention, that we also still do not support implicit measures - that should be coming quite soon.
So for now we only detect direct usage of columns, (explicit) measure and hierarchy levels.

FactSales is shown since channelKey is used on [Data Problems] page:
![image](https://github.com/tabulartools/pbi-explorer/assets/22237520/004053d4-4bf2-4bac-98bc-2e24f63c119d)

As soon as I add a visualization that uses one of the columns from FactOnlineSales, it is also detected:
![image](https://github.com/tabulartools/pbi-explorer/assets/22237520/40d7da4f-2924-4264-a556-0f15daa6df80)

So, what you are seeing is just the state we are in right now.  
It is generally a good idea to [not use implicit measures](https://www.ehansalytics.com/blog/2023/9/29/always-use-explict-measures-wait-what-is-an-explicit-measure) and we haven't prioritized them very high.
But support for them is in the works, and will be added in a coming release.

**Comment by fernandocalero** [comment] 2023-11-13 19:57
Ok. I just used an implicit measure to quickly add something from directly from the fact table to show you.

**Closed as completed** 2023-11-14 07:20 UTC
Labels: bug, untriaged
