### ISSUE TITLE
Tooltips for side bar icons when the side bar is collapsed

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#32] opened 2023-10-02 06:07 UTC
### The feature request

When the side bar on the left is collapsed, it is difficult to tell what the icons at the top of the side bar do without expanding the side bar again.

### Proposed solution

When the side bar is collapsed, the text that is beside the icon when the side bar is expanded should appear in a tooltip upon hovering over the icon.

**Comment by DBojsen** [comment] 2023-10-03 12:18
Duplicate of #10

**Closed as completed by DBojsen** 2023-10-03 12:18 UTC
Labels: enhancement, untriaged
