### ISSUE TITLE
Diff output in html format

### ISSUE THREAD

**Issue by gopakumarlimner** [tabulartools/pbi-explorer#46] opened 2023-10-06 22:27 UTC
### The feature request

Possibility to output the Diff view in HTML format. Similar to the output which is there in the new Pbi Inspector.

### Proposed solution

This will help to document the differences at various stages of development and during further enhancement of the reports. This will be useful in meetings where PBI explorer cannot be used.  

### Additional context

<img width="1016" alt="Img1" src="https://github.com/tabulartools/pbi-explorer/assets/66367870/4b779983-9bb6-44b2-bf0f-dfbc3dd28efd">

**Comment by DBojsen** [comment] 2023-10-07 06:30
Duplicate of #25

**Closed as completed by DBojsen** 2023-10-07 06:30 UTC
Labels: enhancement, untriaged
