### ISSUE TITLE
Adjust nav bar

### ISSUE THREAD

**Issue by rudzimj** [tabulartools/pbi-explorer#29] opened 2023-09-28 20:08 UTC
### The feature request

The bottom buttons on the blue nav bar have hover text, but the top ones don't.
<img width="143" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/36211641/ea677728-517f-439b-8340-fc2b447ad5ac">

As you use the **Inspect report** and **Compare report** tools, the nav bar changes, and the top buttons also need hover text.
<img width="32" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/36211641/fa7b3370-baf7-495e-99ee-07d4e5c7b33f">
<img width="30" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/36211641/5320154f-18aa-4ada-8c14-4b8becad8d62">

The label for the open button **Inspect report** tool is "Open in inspector". I think just "Open" would make more sense. Once you have opened a report, it isn't obvious that you are in the "Inspector".
<img width="102" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/36211641/e87c1865-770d-49e1-adc8-39c5e2a27429">

Then when expanding the bar, the top ones have nice lables, and the bottom ones don't.
<img width="156" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/36211641/44861473-b055-4215-be78-5e0360706ca6">

Maybe someday the icons will be intuitive, but as a new users, the hover text and labels are super helpful.

### Proposed solution

Create hover text for every nav button.
Change "Open in inspector" to Open.
Change tool buttons to be like top buttons with a full label.

**Comment by DBojsen** [comment] 2023-09-29 07:38
Duplicate of #10

**Closed by DBojsen** 2023-09-29 07:38 UTC
Labels: enhancement, untriaged
