### ISSUE TITLE
Support Comparing DAX Expressions 

### ISSUE THREAD

**Issue by relax528** [tabulartools/pbi-explorer#69] opened 2023-11-16 21:28 UTC
### The feature request

When comparing two PBIX files, drilling into Measures shows Type, IsReportMeasure, Name and ReferenceName, but not the DAX expression or other DAX related properties. 

### Proposed solution

Include DAX measure properties as part of the comparison.

**Comment by DBojsen** [comment] 2023-11-20 08:46
Hi @relax528 

This is a duplicate of
https://github.com/tabulartools/pbi-explorer/issues/51.
Please see the answer there: https://github.com/tabulartools/pbi-explorer/issues/51#issuecomment-1776835437

**Closed as completed by DBojsen** 2023-11-20 08:46 UTC
Labels: enhancement, untriaged
