### ISSUE TITLE
DAX Measure Table

### ISSUE THREAD

**Issue by bluebeef71** [tabulartools/pbi-explorer#54] opened 2023-11-05 14:36 UTC
### Describe the problem

PBI explorer report connection to PBIX file that is a Direct Query connection to the dataset.

The created DAX measures table doesn't look visible within the Data Model Explorer

![Screenshot 2023-11-05 at 14 30 19](https://github.com/tabulartools/pbi-explorer/assets/149951081/d2a76c74-10d8-412d-a6b8-67dce2305cd5)

![Screenshot 2023-11-05 at 14 30 38](https://github.com/tabulartools/pbi-explorer/assets/149951081/ad634535-3662-45ce-987d-405c1639f0f9)

### PBI Explorer

0.4.1

### Power BI

Version: 2.121.903.0 64-bit (September 2023)

### Windows

Windows 11 Pro

### Screenshots

![Screenshot 2023-11-05 at 14 30 19](https://github.com/tabulartools/pbi-explorer/assets/149951081/116e7cc2-1048-4ef2-86d2-f23e431082c8)
![Screenshot 2023-11-05 at 14 30 38](https://github.com/tabulartools/pbi-explorer/assets/149951081/8ed22e06-b741-4a40-8c0a-72ea0f6a67c5)

**Comment by DBojsen** [comment] 2023-11-05 21:02
Hi @bluebeef71 

This is a duplicate of #51 .  Please see the answer there: https://github.com/tabulartools/pbi-explorer/issues/51#issuecomment-1776835437

BR David - Tabular Tools

**Closed as completed by DBojsen** 2023-11-05 21:02 UTC
Labels: bug, untriaged
